### ISSUE TITLE
Fee-market improvement

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-bridge-sol#106]
## Issue 
For now design, we reuse the relayer maker fee in order.
So if `relayer` assign and lock their collateral. They can not change their `Maker Fee` at any time.

## Improvement
Store the relayer's `maker fee` in order.
And `relayer` could change their `Maker Fee` at any time.

## Disadvantages
More storage will increase more gas usage.

**Comment by HackFisher** [comment]
Yes, that's an issue, relayer's make fee should be recorded in order after matched/assigned.
