### ISSUE TITLE
Support guard features in mapping token protocol v2

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-bridge-sol#114]
https://github.com/darwinia-network/darwinia-common/issues/755

Related #101 

Guard is supposed to in the application layer.

e.g. When inbound lane call `unlockFromRemote`, it should store the balance instead of transfer to dest instantly, and there is a guard selected by Wormhole DAO who is keeping check and provide signatures to the dest user to withdraw the received token.

There is no audit attacking from guard, since Wormhole DAO can replace the guard if required.

**Comment by HackFisher** [comment]
This guard is removed in truth layer, but can be used as implementation reference for this issue and token layer:

https://github.com/darwinia-network/darwinia-bridge-sol/pull/117

**Comment by xiaoch05** [comment]
related https://github.com/darwinia-network/darwinia-bridge-sol/pull/124
