### ISSUE TITLE
Oracle based message protocol

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-bridge-sol#339]
1. FeeMarket could be a relayer contracts. (meta-tx)
2. ParallelOutboundLane may be a better choice.
3. To solve the centralization problem of oracle, provide redundant security. How to set up additional checking mechanism at message layer?
4. this detection mechanism may introduce censorship/blocking attacks, in the sequential message delivery model. This mechanism may allow us to abandon the sequential delivery model and use only the unordered delivery model. 
5. This detection mechanism can be implemented if the user is allowed to select the specified relayer to deliver the message. But it may be necessary to abstract the fee-market into a relayer contract. 
6. other message authentication methods such as message_root proof may be used, but it is desirable to generalize message authentication while taking into account the cost of gas.

**Comment by jiguantong** [comment]
Layerzero maintains the dest token conversion ratio in the relayer contract, calculates the required cost of the target chain according to the gas specified by the sender, and then converts it into the required native token.
code: https://github.com/LayerZero-Labs/LayerZero/blob/main/contracts/Relayer.sol#L105

**Comment by hujw77** [comment]
https://github.com/darwinia-network/ormp
