### ISSUE TITLE
What is branch mask in mpt?

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-bridge-sol#54]
which will be used in solidity patricia trie proof verification:
https://github.com/chriseth/patricia-trie/blob/1d747641161ce42a6cda3596d1716e8f120262ac/patricia.sol#L82

**Comment by HackFisher** [comment]
@hujw77 Could you help answer this question, and add docs if necessary.

**Comment by hujw77** [comment]
This lib implementation is a trie in a different way than ethereum and substrate, each node is bytes32, and has 2 children, each layer has 256 siblings, `branchmask` is, under the common prefix, the path to the next node, if 0 is the left child node, if 1 is the right child node.
```
/*
 *                      +---------------------------+
 *             bytes32  |1 0 0 1 0 0 1 1 1 0 ...    |
 *                      +----------+----------------+
 *                                 |
 *                                 |
 * +-----------------------+   0   |  1  +------------------------+
 * |1 0 1 0 1 ...          +-------+-----+1 1 0 0 1 ...           |
 * +-----------------------+             +------------------------+
 */
```

**Comment by HackFisher** [comment]
Not used in this repo
