### ISSUE TITLE
Ethereum v1 review

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-bridge-sol#82]
@hujw77 request more explanation

If someone call IBacking(backing).crossChainSync and withdraw his balance, the helper function will be stuck.
https://github.com/darwinia-network/darwinia-bridge-sol/blob/631101dbe6a96ae5127561cb8ee9dec71da1d220/contracts/issuing-backing/contracts/ethereum/BackingHelper.sol#L108

**Comment by hujw77** [comment]
https://github.com/darwinia-network/darwinia-bridge-sol/blob/631101dbe6a96ae5127561cb8ee9dec71da1d220/contracts/issuing-backing/contracts/ethereum/BackingHelper.sol#L104-L114

For a same blockNumber, This helper function do a batch `withraw` wETH to ETH.
But I would only call `IBacking(backing).crossChainSync` and `withraw` for lower gas. 
In this case, this helper function will always revert in the same blockNumber after my call.

**Comment by HackFisher** [comment]
@xiaoch05 Please help check wether these review request are fixed, or link related PR.

**Comment by xiaoch05** [comment]
It becomes complex to help users redeem the ETH native token. 
This will cause the complex of wormhole front-end. And I will delete this helper file. Only allow users to use weth instead.

**Comment by xiaoch05** [comment]
another idea of processing weth=>eth is from anyswap which called router (https://docs.multichain.org/). Also it can be used to swap xUSDT => USDT etc.
This can be used as an alternative for us.
Currently we don't consider the native token specially, and remove this backing helper file.
This has been moved to deprecated by https://github.com/darwinia-network/darwinia-bridge-sol/pull/129.
